- .gitignore
- pom.xml
Fix #19
* In the process of setting up my IDE to build the project, the entries for
Maven plugin management were removed. Also note that in the POM.XML the
compiler source/target entries have been set to "1.11" for JDK 11. I was
unable to compile pull requests containing certain language features until
I updated these entries to a later compiler.
* My IDE made the decision to erase all of the plugin management entries. I'm
going to assume that's because these were placeholders and aren't being used
yet. If their inclusion at this time is necessary, let me know.
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
> Adding IntelliJ-specific files to .gitignore

- src/main/java/com/alvarium/PublishWrapper.java
- src/main/java/com/alvarium/SdkAction.java
- src/main/java/com/alvarium/streams/MockStreamProvider.java
- src/main/java/com/alvarium/streams/StreamException.java
- src/main/java/com/alvarium/streams/StreamProvider.java
- src/main/java/com/alvarium/streams/StreamProviderFactory.java
- src/main/java/com/alvarium/streams/StreamType.java
- src/test/java/com/alvarium/PublishWrapperTest.java
- src/test/java/com/alvarium/publishWrapperData.json
- src/test/java/com/alvarium/streams/StreamProviderTest.java
* add gson dependency to pom.xml
* create SdkAction enum
* create PublishWrapper class with the toJson and
fromJson methods
* create StreamProvider interface
* create general StreamException
* implement MockStreamProvider to conform to the
StreamProvider interface
* implement the StreamProviderFactory
* implement related unit tests
Fix #29
> Define StreamProvider Interface and related factory

- src/main/java/com/alvarium/PublishWrapper.java
- src/main/java/com/alvarium/serializers/AnnotationConverter.java
- src/test/java/com/alvarium/PublishWrapperTest.java
* Add an AnnotationConverter class to override
the serialization process
* Use the implemented serializer in the PublishWrapper
class
* implement unit test
Fix #32
> Add an Annotation serializer to be used in PublishWapper

- src/main/java/com/alvarium/annotators/Annotator.java
- src/main/java/com/alvarium/annotators/AnnotatorException.java
- src/main/java/com/alvarium/annotators/AnnotatorFactory.java
- src/main/java/com/alvarium/annotators/MockAnnotator.java
- src/main/java/com/alvarium/contracts/AnnotationType.java
- src/main/java/com/alvarium/sign/KeyInfo.java
- src/main/java/com/alvarium/sign/SignatureInfo.java
- src/main/java/com/alvarium/utils/PropertyBag.java
- src/test/java/com/alvarium/annotators/AnnotatorTest.java
- src/test/java/com/alvarium/sign/KeyInfoTest.java
- src/test/java/com/alvarium/sign/SignatureInfoTest.java
- src/test/java/com/alvarium/sign/keyInfoData.json
- src/test/java/com/alvarium/sign/signatureInfoData.json
* Add annotator interface
* Add general AnnotatorException type
* Add KeyInfo class as a java bean
* Add SignatureInfo class as a java bean
* Implement MockAnnotator which is used in unit tests
* Implement and expose AnnotatorFactory class
* Implement all related unit tests
Fix #33
> Define Annotator interface and related factory

- src/main/java/com/alvarium/SdkAction.java
- src/main/java/com/alvarium/SdkInfo.java
- src/main/java/com/alvarium/contracts/AnnotationType.java
- src/main/java/com/alvarium/hash/HashInfo.java
- src/main/java/com/alvarium/hash/HashType.java
- src/main/java/com/alvarium/serializers/StreamInfoConverter.java
- src/main/java/com/alvarium/sign/SignType.java
- src/main/java/com/alvarium/streams/StreamType.java
- src/test/java/com/alvarium/SdkInfoTest.java
- src/test/java/com/alvarium/contracts/data.json
- src/test/java/com/alvarium/publishWrapperData.json
- src/test/java/com/alvarium/sdk-info.json
- src/test/java/com/alvarium/sign/keyInfoData.json
- src/test/java/com/alvarium/sign/signatureInfoData.json
- src/test/java/com/alvarium/streams/mqtt-config.json
* Override enum literals serialization to match lowercase
implemention of the go sdk
* Add HashInfo as a Java bean
* Add SdkInfo as a Java bean
* Implement unit tests
Fix #38 & Fix #42
> Enable sdk configuration driven customization

- pom.xml
- src/main/java/com/alvarium/DefaultSdk.java
- src/main/java/com/alvarium/Sdk.java
- src/test/java/com/alvarium/SdkInfoTest.java
- src/test/java/com/alvarium/SdkTest.java
- src/test/java/com/alvarium/mock-info.json
* Add the required params to the Sdk Constructor
* Implement a close() method to cleanup the sdk
* Fix previous unit tests depending on the SdkInfo
* Implement related unit tests
Fix #49
> Implement Sdk constructor

- src/main/java/com/alvarium/annotators/AnnotatorFactory.java
- src/main/java/com/alvarium/annotators/PkiAnnotator.java
- src/main/java/com/alvarium/annotators/Signable.java
- src/main/java/com/alvarium/contracts/AnnotationType.java
- src/test/java/com/alvarium/annotators/PkiAnnotatorTest.java
Fix #48
* Add signable java bean
* Create private method on PKI annotator for verifying signatures
* Implement unit tests for the annotator
> Add PKI Annotator implementation

- src/main/java/com/alvarium/DefaultSdk.java
- src/main/java/com/alvarium/Sdk.java
- src/test/java/com/alvarium/SdkTest.java
- src/test/java/com/alvarium/mock-info.json
* modify the create method on the sdk interface to throw
annotator and stream exceptions
* implement the create method on the DefaultSdk
* implement related unit tests
Fix #56
> Implement the create() method of sdk interface

- src/main/java/com/alvarium/DefaultSdk.java
- src/main/java/com/alvarium/Sdk.java
- src/test/java/com/alvarium/SdkTest.java
* modify the transit method on the sdk interface to
throw Annotator and Stream Exceptions
* implement the transit method on the DefaultSdk
* implement related unit tests
Fix #57
> Implement transit() method of sdk interface

- src/test/java/com/alvarium/streams/MqttStreamProviderTest.java
Fix #66
* Removed `MqttStreamProvider` unit tests that required an available MQTT endpoint
* Added unit tests which ensure that the stream configuration is loaded does not fail when casting to `MqttConfig`
> Remove MQTT unit tests that depended on an available endpoint

- src/main/java/com/alvarium/annotators/AnnotatorUtils.java
- src/main/java/com/alvarium/annotators/PkiAnnotator.java
- src/main/java/com/alvarium/annotators/SourceAnnotator.java
- src/main/java/com/alvarium/annotators/TlsAnnotator.java
- src/main/java/com/alvarium/annotators/TpmAnnotator.java
Fix #58
* Changed the name of `AnnotatorUtils` to `AbstractAnnotator` so that it follows the Java naming convention for abstract classes
> Change abstract class name AnnotatorUtils to AbstractAnnotator

- src/main/java/com/alvarium/DefaultSdk.java
- src/main/java/com/alvarium/Sdk.java
- src/test/java/com/alvarium/SdkTest.java
Fix #67
* Overload SDK methods to be able to call them without passing a property bag
> Overload SDK methods for reduced boilerplate

- pom.xml
Fix #85
* Update log4j dependency from 2.14.1 to 2.15.0
> Bump log4j dependency

- src/test/java/com/alvarium/utils/EncoderTest.java
Fix #87
* Use "NativePRNG" to tap into `/dev/urandom` for random number generation
> Fix intermittent hanging in Encoder unit test

- src/main/java/com/alvarium/contracts/AnnotationType.java
* change AnnotationType.SOURCE serialization value to "src"
Fix #91
Signed-off-by: Karim Elghamry <karim_elghamry@dell.com>
> AnnotationType source does not conform to the go sdk implementation

- src/main/java/com/alvarium/Sdk.java
- src/main/java/com/alvarium/annotators/AbstractPkiAnnotator.java
- src/main/java/com/alvarium/annotators/AnnotatorFactory.java
- src/main/java/com/alvarium/annotators/PkiAnnotator.java
- src/main/java/com/alvarium/annotators/PkiHttpAnnotator.java
- src/main/java/com/alvarium/contracts/AnnotationType.java
- src/test/java/com/alvarium/annotators/PkiHttpAnnotatorTest.java
* Add AbstractPkiAnnotator
* Add PkiHttpAnnotator
* Add PkiHttp to AnnotatorFactory
* Add PkiHttp to AnnotationType
* Add PkiHttpAnnotator tests
Fix #93
Signed-off-by: Mohanad <mohanadismail789@gmail.com>
> Add Support for Signature Validation via HTTP Header

- Jenkinsfile
- src/main/java/com/alvarium/annotators/AnnotatorFactory.java
- src/main/java/com/alvarium/annotators/SourceCodeAnnotator.java
- src/main/java/com/alvarium/annotators/SourceCodeAnnotatorProps.java
- src/main/java/com/alvarium/contracts/AnnotationType.java
- src/main/java/com/alvarium/hash/HashProvider.java
- src/main/java/com/alvarium/hash/Md5Provider.java
- src/main/java/com/alvarium/hash/NoneProvider.java
- src/main/java/com/alvarium/hash/Sha256Provider.java
- src/test/java/com/alvarium/annotators/SourceCodeAnnotatorTest.java
- src/test/java/com/alvarium/hash/HashProviderTest.java
* Implement a `SourceCodeUtil` class that abstracts reading directory
files and hashing them
* Add `update()` and `getValue()` methods to the hash provider to
enable hashing by parts. This was used to hash each file in the
source code util without loading all files into a buffer
* Implement the `SourceCodeAnnotator` which replaced the proposed
git annotator. This annotator takes a path to a checksum and a
path to the source code directory and does the required verification
to match the source code with the provided checksum.
* Implemented relevant unit tests
* Add missing `@Override` decorators to `HashProvider` implementations
* Add `SourceCodeAnnotatorProps` class to facilitate passing
multi-valued ctx to annotator
- The changes in this …
> Add SourceCodeAnnotator implementation and relevant tests

- src/test/java/com/alvarium/utils/EncoderTest.java
Fix #101
- Use default algorithm provided by SecureRandom instead of specifying one
might be related to #87.
> Fix exception being thrown from encoder unit tests on windows

- src/main/java/com/alvarium/annotators/AnnotatorFactory.java
- src/main/java/com/alvarium/annotators/ChecksumAnnotator.java
- src/main/java/com/alvarium/annotators/ChecksumAnnotatorProps.java
- src/main/java/com/alvarium/contracts/AnnotationType.java
- src/main/java/com/alvarium/hash/HashProvider.java
- src/main/java/com/alvarium/hash/Md5Provider.java
- src/main/java/com/alvarium/hash/Sha256Provider.java
- src/test/java/com/alvarium/annotators/ChecksumAnnotatorTest.java
* Add `ARTIFACT` annotator type
* Add `ArtifactAnnotatorProps` class that takes artifact and checksum paths
* Add `ArtifactAnnotator` implementation where it generates the checksum of an existing artifact and matches is against an existing checksum
* Add another signature for the hash provider's `update()` method where the offset and size of the bytes intended for hashing can be specified. This is useful when hashing large files in chunks to be able to handle the EOF case where not the entire buffer is hydrated
> Add ChecksumAnnotator and relevant tests

- src/main/java/com/alvarium/annotators/ChecksumAnnotatorProps.java
Fix #106
Changed the `ArtifactAnnotatorProps` class name to `ChecksumAnnotatorProps`
> Change checksum annotator properties class name

- src/main/java/com/alvarium/serializers/StreamInfoConverter.java
Fix #113
Used `gson.fromJson()` to deserialize the StreamType value in the StreamInfoConverter class to allow it to use the SerializedName decorator instead of bypassing it
> Fix possible issue in stream provider deserializer for complex names

- src/main/java/com/alvarium/DefaultSdk.java
- src/main/java/com/alvarium/SdkInfo.java
- src/main/java/com/alvarium/annotators/AnnotatorConfig.java
- src/main/java/com/alvarium/annotators/AnnotatorFactory.java
- src/main/java/com/alvarium/annotators/MockAnnotator.java
- src/main/java/com/alvarium/annotators/MockAnnotatorConfig.java
- src/main/java/com/alvarium/annotators/VulnerabilityAnnotator.java
- src/main/java/com/alvarium/serializers/AnnotatorConfigConverter.java
- src/test/java/com/alvarium/SdkInfoTest.java
- src/test/java/com/alvarium/annotators/AnnotatorTest.java
- src/test/java/com/alvarium/annotators/ChecksumAnnotatorTest.java
- src/test/java/com/alvarium/annotators/PkiAnnotatorTest.java
- src/test/java/com/alvarium/annotators/PkiHttpAnnotatorTest.java
- src/test/java/com/alvarium/annotators/SourceAnnotatorTest.java
- src/test/java/com/alvarium/annotators/SourceCodeAnnotatorTest.java
- src/test/java/com/alvarium/annotators/TlsAnnotatorTest.java
- src/test/java/com/alvarium/annotators/TpmAnnotatorTest.java
- src/test/java/com/alvarium/annotators/VulnerabilityAnnotatorTest.java
- src/test/java/com/alvarium/mock-info.json
- src/test/java/com/alvarium/sdk-info.json
Fix #110
* Add a new AnnotatorInfo class along with its deserializer and use it in place of annotator kind when instantiating annotators
* Adjust unit tests accordingly
* Enable the configuration of the MockAnnotator to be either satisfied or not satisfied
* Move the ServiceInfo class to a common package to enable future annotators that use external API's to use it
> Add support for annotator-speicific configuration

- src/main/java/com/alvarium/annotators/AnnotatorFactory.java
- src/main/java/com/alvarium/annotators/VulnerabilityAnnotator.java
- src/main/java/com/alvarium/annotators/vulnerability/OsvApiHandler.java
- src/main/java/com/alvarium/annotators/vulnerability/VulnerabilityAnnotatorConfig.java
- src/main/java/com/alvarium/annotators/vulnerability/VulnerabilityApiHandlerFactory.java
- src/main/java/com/alvarium/annotators/vulnerability/VulnerabilityProviderType.java
- src/main/java/com/alvarium/serializers/AnnotatorConfigConverter.java
- src/main/java/com/alvarium/streams/MqttConfig.java
- src/main/java/com/alvarium/streams/PravegaConfig.java
- src/main/java/com/alvarium/utils/ServiceInfo.java
- src/test/java/com/alvarium/SdkInfoTest.java
- src/test/java/com/alvarium/annotators/vulnerability/OsvApiHandlerTest.java
- src/test/java/com/alvarium/annotators/vulnerability/VulnerabilityApiHandlerFactoryTest.java
- src/test/java/com/alvarium/sdk-info.json
Fix #114
* Add new VulnerabilityAnnotatorConfig type and hydrate it from the SDK config
* Move ServiceInfo to contracts for use by multiple packages
> Add capability to pass vulnerability source to annotator through config

- src/main/java/com/alvarium/DefaultSdk.java
- src/main/java/com/alvarium/annotators/AbstractAnnotator.java
- src/main/java/com/alvarium/annotators/AbstractPkiAnnotator.java
- src/main/java/com/alvarium/annotators/AnnotatorFactory.java
- src/main/java/com/alvarium/annotators/ChecksumAnnotator.java
- src/main/java/com/alvarium/annotators/PkiAnnotator.java
- src/main/java/com/alvarium/annotators/PkiHttpAnnotator.java
- src/main/java/com/alvarium/annotators/SourceAnnotator.java
- src/main/java/com/alvarium/annotators/SourceCodeAnnotator.java
- src/main/java/com/alvarium/annotators/TlsAnnotator.java
- src/main/java/com/alvarium/annotators/TpmAnnotator.java
- src/main/java/com/alvarium/annotators/VulnerabilityAnnotator.java
- src/test/java/com/alvarium/SdkTest.java
- src/test/java/com/alvarium/annotators/AnnotatorTest.java
- src/test/java/com/alvarium/annotators/ChecksumAnnotatorTest.java
- src/test/java/com/alvarium/annotators/PkiAnnotatorTest.java
- src/test/java/com/alvarium/annotators/PkiHttpAnnotatorTest.java
- src/test/java/com/alvarium/annotators/SourceAnnotatorTest.java
- src/test/java/com/alvarium/annotators/SourceCodeAnnotatorTest.java
- src/test/java/com/alvarium/annotators/TlsAnnotatorTest.java
- src/test/java/com/alvarium/annotators/TpmAnnotatorTest.java
- src/test/java/com/alvarium/annotators/VulnerabilityAnnotatorTest.java
Fix #111 
- Refactored all Annotators to continue execution when an error occurs, returning an unsatisfied Annotation.
- Pass the Logger to the Annotators execute method to log the thrown exceptions.
- Refactored tests that expected Annotators execute to throw an exception to expect an unsatisfied Annotation.
Notes:
- The host is defaulted to an empty string in case fetching the host name throws an error so we can return an unsatisfied annotation.
- While executing The PkiHttpAnnotator the http signature logic may throw exceptions that will halt the execution as there will be no key to sign the annotation.
> Refactor Annotators to continue execution on error

- src/main/java/com/alvarium/annotators/VulnerabilityAnnotator.java
FIX #122 
- Wrap the getPackages call in the try catch block in the VunlerabilityAnnotator to publish an unsatisfied annotation when exception is thrown during scanning package file
> Wrap getPackages() call in the try-catch block

- src/main/java/com/alvarium/annotators/vulnerability/GoModHandler.java
- src/main/java/com/alvarium/annotators/vulnerability/PackageFileHandlerFactory.java
- src/test/java/com/alvarium/annotators/vulnerability/GoModHandlerTest.java
- src/test/java/com/alvarium/annotators/vulnerability/PackageFileHandlerFactoryTest.java
Fix #121
- Add GoModHandler that implements PackageHandler Interface
- Add the GoModHandler to the PackageFileHandlerFactory to be returned if a go.mod file exists.
- Add unit tests for GoModHandler and the factory.
> Add support for go.mod files in VulnerabilityAnnotator

- src/main/java/com/alvarium/annotators/SourceCodeAnnotator.java
- src/test/java/com/alvarium/annotators/SourceCodeAnnotatorTest.java
Fix #124
- Refactored the checksum generation to match the following bash command:
```find "$PATH" -type f -exec md5sum {} + | LC_ALL=C sort | md5sum```
- List all files recursively in the given directory.
- Hash each file and concatenated its hash before it. Ex: ```ACBD18DB4CC2F85CEDEF654FCCC4A4D8  /path/file```
- Sort the list of strings checksum path string using the "US" locale to ensure consistent sorting.
- Hash the combined string to return the generated source code checksum.
Combined String Ex:
```
ACBD18DB4CC2F85CEDEF654FCCC4A4D8  /path/file
AE3E83E2FAB3A7D8683D8EEFABD1E74D  /path/file2
```
> The string always ends with a new line to match the output of the bash command.
- Implemented the getAllFiles method to recursively list all files in the directory and its subdirectories.
- …
> Refactor SourceCodeAnnotator hashing methodology to match that of external tools
